services:
  firestore:
    build: ./docker/firestore
    networks:
      - backend-net
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8000"]
      interval: 2s
      timeout: 2s
      retries: 30

  finapp-backend:
    environment:
      FIRESTORE_EMULATOR_HOST: firestore:8000
      GCP_PROJECT_ID: local-dev
    depends_on:
      firestore:
        condition: service_healthy
